app_name: myapp

watch:
  - ./
  - ./cmd
  - ./internal

ignore:
  - .git
  - .idea
  - .vscode
  - "*.md"
  - "*.yml"
  - .air.yaml

build:
  bin: myapp
  cmd: go test ./... && go build -o ./myapp ./main.go

run:
  cmd: ./myapp 

