services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "8080:8080"
    networks:
      - cs2_network
    depends_on:
      - db
    restart: always
    volumes:
      - .:/app
      - air_config:/root/.air.yaml # Custom Air config file
    working_dir: /app
    command: sh -c "air"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Bind mount your custom nginx.conf
    ports:
      - "80:80"  # Exposing Nginx on port 80
    networks:
      - cs2_network  # Make sure Nginx is on the same network
    depends_on:
      - api  # Ensure Nginx waits for the api service
    restart: always

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: go test ./...
    depends_on:
      - db
    networks:
      - cs2_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init/db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql
    networks:
      - cs2_network
    ports:
      - "5432:5432"
    restart: always

volumes:
  db_data:
  air_config: # Volume for custom Air config

networks:
  cs2_network:
    driver: bridge
